# Generated by Django 3.1.2 on 2022-11-25 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countrylist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countrylist',
            name='ISO_A3',
        ),
        migrations.AlterField(
            model_name='countrylist',
            name='id',
            field=models.CharField(max_length=3, primary_key=True, serialize=False),
        ),
    ]
