# Generated by Django 3.1.2 on 2022-11-24 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lawapi', '0001_initial'),
        ('thematicapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=500)),
                ('ISO_A3', models.CharField(max_length=3)),
                ('flag', models.ImageField(upload_to='images')),
                ('summaryStatement', models.TextField()),
                ('otherLaws', models.ManyToManyField(blank=True, to='lawapi.Law')),
                ('thematic_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thematicapi.thematicarea')),
            ],
        ),
    ]
