# Generated by Django 3.1.2 on 2022-11-25 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lawapi', '0003_auto_20221125_1039'),
        ('countrylist', '0001_initial'),
        ('thematicapi', '0003_auto_20221125_1044'),
        ('sadcapi', '0002_auto_20221125_1049'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Country',
            new_name='CountryData',
        ),
    ]
