# Generated by Django 3.1.2 on 2022-11-24 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThematicArea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('country_of_focus', models.CharField(max_length=100)),
                ('easy_of_registration', models.FloatField()),
                ('compliance', models.FloatField()),
                ('tax', models.FloatField()),
                ('incentives', models.FloatField()),
                ('movements_of_financial_resources', models.FloatField()),
                ('support_for_civil_rights', models.FloatField()),
            ],
        ),
    ]
