# Generated by Django 3.1.2 on 2022-11-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thematicapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thematicarea',
            name='compliance',
            field=models.FloatField(max_length=1),
        ),
        migrations.AlterField(
            model_name='thematicarea',
            name='easy_of_registration',
            field=models.FloatField(max_length=1),
        ),
        migrations.AlterField(
            model_name='thematicarea',
            name='incentives',
            field=models.FloatField(max_length=1),
        ),
        migrations.AlterField(
            model_name='thematicarea',
            name='movements_of_financial_resources',
            field=models.FloatField(max_length=1),
        ),
        migrations.AlterField(
            model_name='thematicarea',
            name='support_for_civil_rights',
            field=models.FloatField(max_length=1),
        ),
        migrations.AlterField(
            model_name='thematicarea',
            name='tax',
            field=models.FloatField(max_length=1),
        ),
    ]
