# Generated by Django 3.1.2 on 2022-11-25 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countrylist', '0001_initial'),
        ('thematicapi', '0002_auto_20221124_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thematicarea',
            name='country_of_focus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='countrylist.countrylist'),
        ),
    ]
