# Generated by Django 3.1.2 on 2022-11-24 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Law',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('targeted_country', models.CharField(blank=True, default='', max_length=500)),
                ('law', models.CharField(blank=True, default='', max_length=500)),
                ('law_description', models.TextField(blank=True, default='')),
                ('source_name', models.TextField(blank=True, default='')),
                ('source_link', models.CharField(blank=True, default='', max_length=500)),
            ],
        ),
    ]
