# Generated by Django 3.1.2 on 2022-11-25 06:53

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('lawapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='law',
            name='law',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='law',
            name='law_description',
            field=tinymce.models.HTMLField(),
        ),
    ]
