# Generated by Django 3.1.2 on 2022-11-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawapi', '0003_auto_20221125_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='law',
            name='law_files',
            field=models.ImageField(blank=True, upload_to='law-files'),
        ),
        migrations.AlterField(
            model_name='law',
            name='law',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='law',
            name='source_name',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
