# Generated by Django 3.1.2 on 2022-11-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawapi', '0004_auto_20221129_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='law',
            name='law_files',
            field=models.FileField(blank=True, upload_to='law-files'),
        ),
    ]
